apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
stringData: 
  credentials: |
    [default]
    aws_access_key_id = AKIA6LTSLEXXLSHAOB56
    aws_secret_access_key = 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